### ISSUE TITLE
secretOrPrivateKey must have a value

### ISSUE THREAD

**Issue by ahmadxgani** [ForumLinuxIndonesia/userauth-backend#1]
i try to hit refresh token endpoint and got error "secretOrPrivateKey must have a value", it seems argument of secretOrPrivateKey is undefined, so i try to `console.log(isRefresh ? process.env.JWT_SECRET_REFRESH : process.env.JWT_SECRET)` and make sure the arguments are filled in, but still got same error, how to fix it?

error log:
```bash
    return failure(new Error('secretOrPrivateKey must have a value'));
                   ^

Error: secretOrPrivateKey must have a value
    at module.exports [as sign] (/home/zero/Desktop/github/userauth-backend/node_modules/jsonwebtoken/sign.js:107:20)
    at renewTokenUser (file:///home/zero/Desktop/github/userauth-backend/src/services/auth.service.js:47:39)
    at refreshController (file:///home/zero/Desktop/github/userauth-backend/src/controllers/refresh.controller.js:11:18)
    at Layer.handle [as handle_request] (/home/zero/Desktop/github/userauth-backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/zero/Desktop/github/userauth-backend/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/zero/Desktop/github/userauth-backend/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/zero/Desktop/github/userauth-backend/node_modules/express/lib/router/layer.js:95:5)
    at /home/zero/Desktop/github/userauth-backend/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/zero/Desktop/github/userauth-backend/node_modules/express/lib/router/index.js:346:12)
    at next (/home/zero/Desktop/github/userauth-backend/node_modules/express/lib/router/index.js:280:10)
```

**Comment by hansputera** [comment]
Have you fill the `JWT_SECRET_REFRESH` in .env?

**Comment by ahmadxgani** [comment]
yes, I have filled it

**Comment by hansputera** [comment]
Have you debugged the process.env?

**Comment by ahmadxgani** [comment]
i try to `console.log(process.env.JWT_SECRET_REFRESH)` and the value is defined

**Comment by hansputera** [comment]
That's weird, could I see your .env file? (censor the MONGODB_URL if you are using external mongodb server)

**Comment by WaxArsatia** [comment]
Already verify also happen on production side with same error @hansputera

**Comment by WaxArsatia** [comment]
Because there is commit to fix this bug and already tested on server side i will close this issue, open new one if this is still happen.
